# Generated by Django 5.1.6 on 2025-05-06 18:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=122)),
                ('lastname', models.CharField(max_length=122)),
                ('email', models.CharField(max_length=122)),
                ('phone', models.CharField(max_length=12)),
                ('city', models.CharField(max_length=122)),
                ('country', models.CharField(max_length=122)),
                ('pincode', models.CharField(max_length=10)),
                ('linkedin', models.CharField(max_length=122, null=True)),
                ('portfolio', models.CharField(max_length=122, null=True)),
                ('date', models.DateField(default=datetime.datetime.today)),
            ],
        ),
    ]
