# Generated by Django 5.1.6 on 2025-05-07 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute_name', models.CharField(max_length=122)),
                ('institute_location', models.CharField(max_length=122)),
                ('degree', models.CharField(max_length=122)),
                ('graduation_month', models.CharField(max_length=122)),
                ('graduation_year', models.CharField(max_length=122)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.studentdata')),
            ],
        ),
    ]
