# Generated by Django 5.1.6 on 2025-05-07 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_skillsdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skillsdata',
            name='student',
        ),
        migrations.DeleteModel(
            name='EducationData',
        ),
        migrations.DeleteModel(
            name='SkillsData',
        ),
        migrations.DeleteModel(
            name='StudentData',
        ),
    ]
