# Generated by Django 5.1.6 on 2025-05-07 07:32

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main_app', '0004_remove_skillsdata_student_delete_educationdata_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=122)),
                ('lastname', models.CharField(max_length=122)),
                ('email', models.CharField(max_length=122)),
                ('phone', models.CharField(max_length=12)),
                ('city', models.CharField(max_length=122)),
                ('country', models.CharField(max_length=122)),
                ('pincode', models.CharField(max_length=10)),
                ('linkedin', models.CharField(max_length=122, null=True)),
                ('portfolio', models.CharField(max_length=122, null=True)),
                ('date', models.DateField(default=datetime.datetime.today)),
            ],
        ),
        migrations.CreateModel(
            name='SkillsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills', models.TextField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.studentdata')),
            ],
        ),
        migrations.CreateModel(
            name='EducationData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute_name', models.CharField(max_length=122)),
                ('institute_location', models.CharField(max_length=122)),
                ('degree', models.CharField(max_length=122)),
                ('fieldOfStudy', models.CharField(max_length=122)),
                ('graduation_month', models.CharField(max_length=122)),
                ('graduation_year', models.CharField(max_length=122)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.studentdata')),
            ],
        ),
    ]
