# Generated by Django 5.1.6 on 2025-05-07 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillsdata',
            name='project_desc',
            field=models.TextField(default="I am a front-end developer with more than 3 years of experience writing html, css, and js. I'm motivated, result-focused and seeking a successful team-oriented company with opportunity to grow."),
        ),
        migrations.AddField(
            model_name='skillsdata',
            name='project_name',
            field=models.CharField(default='DSP', max_length=122),
        ),
        migrations.AddField(
            model_name='studentdata',
            name='person_desc',
            field=models.TextField(default="I am a front-end developer with more than 3 years of experience writing html, css, and js. I'm motivated, result-focused and seeking a successful team-oriented company with opportunity to grow."),
        ),
    ]
